// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjxsrvqvzxhersvmpyuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqeHNydnF2enhoZXJzdm1weXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNzU3NDEsImV4cCI6MjA1Nzk1MTc0MX0.FRnUNu22989yUa21fS2oAVpsV9TzivONNdUdya4w1_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);